# 工作流名称
name: Process PDF and Generate Book

# 触发条件：推送到 main 分支时，或手动触发
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # 任务名称
  process:
    # 运行环境
    runs-on: ubuntu-latest

    steps:
      # 步骤1: 检出代码，这样工作流才能访问你的仓库文件
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2: 设置 Python 3.11 环境
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 步骤3: 安装依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyMuPDF

      # 步骤4: 运行你的 Python 脚本
      # 假设你的脚本名为 main.py，并且它会处理 'your_document.pdf' 并输出到 'mybook' 目录
      - name: Run PDF processing script
        run: python main.py # <-- 【修改点1】将这里替换为你的实际脚本文件名

      # 步骤5: 提交并推送生成的文件
      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 设置提交信息，可以自定义
          commit_message: "docs: Auto-generate book from PDF"
          
          # 【修改点2】指定要提交的目录。这非常重要！
          # 它会提交 'mybook' 目录下的所有新增和修改过的文件。
          file_pattern: mybook/*
          
          # 设置提交者的身份信息
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>